#!/bin/zsh

HERE="$(dirname "$(readlink -f "$0")")"
ROOT="$(readlink -f "${HERE}/..")"

local gxx_options=(
    "--std=c++14" "-O2" "-Wall" "-Wextra" "-Wshadow" "-Wno-unused-result"
    "-fsanitize=undefined,address" "-DWAFDAYO"
)

export COMPETE_GXX_OPTIONS="${gxx_options[*]}"
export PATH="${ROOT}/bin:${PATH}"
alias gxx="g++ ${COMPETE_GXX_OPTIONS}"
