#!/bin/sh

set -ue

THIS="$(readlink -f "$0")"
HERE="$(cd "$(dirname "$THIS")"; pwd)"
TEMPLATES="$HERE/../templates"

for dest in "$@"; do
	cp -nv "$TEMPLATES/main.cpp" "$dest"
done
cp -nv "$TEMPLATES/dbg.hpp" "dbg.hpp"
